directories: 
  - "/workspace/ywh_data/DataProcessNew/pexels1k/videos_step1_filtered"

threed_json_dirs:
  - "/workspace/ys_data/filtered_data_new/data_pexels1k/keypoints"
  
reshape_scale: 0
points_only_flag: False
show_feet_flag: False
pose_type: "dwpose+3dpose"
target_representation_suffix: "_3dpose_test"
remove_last_flag: True
keypoints_suffix_dwpose: "_keypoints"