# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/DataProcessNew/hd_movie_video_data/videos_step1"
  - "/workspace/ywh_data/DataProcessNew/jilupian_dongman_videos/videos_step1"
  - "/workspace/ywh_data/DataProcessNew/biaobei_CN_JP_KR/videos_step1"
  - "/workspace/ywh_data/DataProcessNew/panda70m/videos_step1"
  

num_workers_per_proc: 8 
remove_last: True
single_gpu_test: False  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: True
  save_mp4: False
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"