# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ys_data/evaluation_300/DWPose/videos"


num_workers_per_proc: 8
remove_last: False
single_gpu_test: True  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: False
  save_mp4: True
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"